spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_app
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Naruto12@#

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate