spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_app
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
api.security.token.secret=senha_super_secreta_hospital_123